'use client'

import { FilePlus2, History, MessageSquare, X, Sparkles, Trash2 } from 'lucide-react'
import type { Chat } from '@/lib/types'

export function Sidebar({ chats, activeChat, onSelect, onNew, onDelete, open, onClose }: { chats: Chat[]; activeChat: string | null; onSelect: (id: string) => void; onNew: () => void; onDelete: (chat: Chat) => void; open: boolean; onClose: () => void }) {
  return <><div className={`fixed inset-0 z-30 bg-slate-950/40 backdrop-blur-sm transition-opacity duration-300 ${open ? 'opacity-100' : 'pointer-events-none opacity-0'}`} onClick={onClose} /><aside className={`glass-surface fixed inset-y-0 left-0 z-40 flex w-[min(21rem,88vw)] flex-col rounded-none border-y-0 border-l-0 shadow-2xl shadow-slate-950/20 transition-transform duration-300 ${open ? 'translate-x-0' : '-translate-x-full'}`}>
    <div className="flex items-center justify-between border-b border-white/50 px-5 py-5 dark:border-white/10"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-500/10 text-indigo-500 dark:bg-indigo-400/10 dark:text-indigo-300"><History size={16} /></div><div><h2 className="text-sm font-bold text-slate-900 dark:text-white">Your assignments</h2><p className="text-[11px] text-slate-500 dark:text-slate-400">Saved writing sessions</p></div></div><button onClick={onClose} className="rounded-xl p-2 text-slate-500 transition hover:bg-white/50 dark:text-slate-400 dark:hover:bg-white/10" aria-label="Close chat history"><X size={18} /></button></div>
    <button className="btn-primary mx-4 mt-5" onClick={onNew}><FilePlus2 size={17} /> New assignment</button>
    <div className="scrollbar-hide flex-1 overflow-y-auto px-3 py-6">{chats.length ? chats.map(chat => <div key={chat.id} className={`group mb-1 flex items-start gap-2 rounded-xl px-3 py-2 transition duration-200 ${activeChat === chat.id ? 'bg-indigo-50 shadow-sm ring-1 ring-indigo-200 dark:bg-indigo-500/15 dark:ring-indigo-400/20' : 'hover:bg-slate-100 dark:hover:bg-white/5'}`}><button onClick={() => onSelect(chat.id)} className="flex min-w-0 flex-1 items-start gap-3 py-1 text-left"><MessageSquare size={16} className={`mt-0.5 shrink-0 ${activeChat === chat.id ? 'text-indigo-500' : 'text-slate-400 dark:text-slate-500'}`} /><span className="min-w-0"><span className={`block truncate text-sm font-medium ${activeChat === chat.id ? 'text-indigo-700 dark:text-indigo-200' : 'text-slate-700 dark:text-slate-300'}`}>{chat.title}</span><span className="mt-1 block text-[11px] text-slate-400 dark:text-slate-500">{new Date(chat.created_at).toLocaleDateString()}</span></span></button><button onClick={() => onDelete(chat)} className="min-h-10 min-w-10 rounded-lg p-2 text-slate-400 transition hover:bg-red-500/10 hover:text-red-500" aria-label={`Delete ${chat.title}`}><Trash2 size={16} /></button></div>) : <div className="px-4 py-10 text-center"><Sparkles size={22} className="mx-auto text-indigo-400" /><p className="mt-3 text-xs leading-5 text-slate-500 dark:text-slate-400">Your saved assignments will appear here.</p></div>}</div>
    <div className="border-t border-slate-200/80 p-4 text-[11px] text-slate-400 dark:border-white/10 dark:text-slate-500">Assignment Writing · Personal workspace</div>
  </aside></>
}
